name: Deploy Azure Functions with Event Grid

on:
  push:
    branches: [ main ]
    paths:
      - 'azure-functions/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'rishi-platform-functions'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-functions'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Configure Event Grid Integration'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          # Create Event Grid topics
          az eventgrid topic create --name rishi-bookings --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --location eastus2
          az eventgrid topic create --name rishi-staff --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --location eastus2
          az eventgrid topic create --name rishi-organization --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --location eastus2
          az eventgrid topic create --name rishi-rbac --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --location eastus2
          az eventgrid topic create --name rishi-analytics --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --location eastus2
          
          # Create Event Grid subscriptions to Azure Functions
          az eventgrid event-subscription create \
            --name booking-events-subscription \
            --source-resource-id /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.EventGrid/topics/rishi-bookings \
            --endpoint-type azurefunction \
            --endpoint /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.Web/sites/${{ env.AZURE_FUNCTIONAPP_NAME }}/functions/BookingEventProcessor